### ISSUE TITLE
packagecloud.io http 500 error on RPMs built with v0.120.x

### ISSUE THREAD

**Issue by joemiller** [goreleaser/goreleaser#1229]
**Describe the bug**

Since the new RPM code in nfpm and goreleaser 0.120.x was introduced it is no longer possible to push RPMs to packagecloud.io.

Packagecloud support response:

> This package is missing a lot of required RPM headers that *must* appear in the YUM metadata so that YUM can find this package and install it from a repository.
>
> I would suggest that the maintainer of this package spend some time reviewing the RPM documentation and/or requesting the tool they use for generating the RPM automatically all required RPM headers. There's lots of possible malformed RPM packages that will make our system 500; we catch a lot of the cases, but we do miss a few and will still 500 in some rare, isolated cases (like this package, which is significantly malformed).

**To Reproduce**

It should be possible to reproduce this bug locally from the https://github.com/pantheon-systems/pauditd project:

```console
git clone git@github.com:pantheon-systems/pauditd.git
cd pauditd

curl -sL https://git.io/goreleaser | bash -s -- --snapshot --rm-dist
```

push to an existing packagecloud.io repo:

```console
$ package_cloud push xxx/xxx/el/8 dist/*rpm

Looking for repository at xxx/xxx... success!
Pushing dist/pauditd-v1.1.11-next-1572710235-x86_64.rpm... Traceback (most recent call last):
        23: from /usr/local/bin/package_cloud:22:in `<main>'
        22: from /usr/local/bin/package_cloud:22:in `load'
        21: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/bin/package_cloud:4:in `<top (required)>'
        20: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        19: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        18: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        17: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        16: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:108:in `push'
        15: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
        14: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:168:in `block in push'
        13: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:168:in `each'
        12: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:178:in `block (2 levels) in push'
        11: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
        10: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:182:in `block (3 levels) in push'
         9: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:242:in `create_package'
         8: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/repository.rb:52:in `create_package'
         7: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
         6: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
         5: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
         4: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/net/http.rb:920:in `start'
         3: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
         2: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
         1: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response': 500 Internal Server Error (RestClient::InternalServerError)
```

**Additional context**

Workaround is to use goreleaser v0.119.3, the last release before the nfpm rpm refactor.

Apologies I cannot provide more details at this time. If I am able to determine anything helpful I'll update this thread.

**Comment by caarlos0** [comment]
any idea of which fields are missing? I don't believe the rpm is significantly malformed as I manually checked some on fedora when we were still working on the migration...

cc/ @djgilcrease as well

**Comment by joemiller** [comment]
I do not. I will try poking around the RPM metadata from a pre-0.120
version for comparison and let you know if I find anything.

**Comment by joemiller** [comment]
A quick peek with `rpm -qpi`:

GOOD (v0.119.0):
```
Name        : pauditd
Version     : 1.1.11_next
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Tools
Size        : 9052160
License     : MIT
Signature   : (none)
Source RPM  : pauditd-1.1.11_next-1.src.rpm
Build Date  : Mon Nov  4 18:12:08 2019
Build Host  : MacBook-Pro
Relocations : (not relocatable)
Packager    : engineering <engineering@pantheon.io>
URL         : https://github.com/pantheon-systems/pauditd
Summary     : go alternative to auditd
Description :
go alternative to auditd
```

BAD (v0.120.3):
```
Name        : pauditd
Version     : 1.1.11-next
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : 
Size        : 9052160
License     : MIT
Signature   : (none)
Source RPM  : pauditd-1.1.11-next-1.src.rpm
Build Date  : (none)
Build Host  : (none)
Relocations : (not relocatable)
Packager    : engineering <engineering@pantheon.io>
Vendor      : Pantheon Systems
URL         : https://github.com/pantheon-systems/pauditd
Summary     : (none)
Description :
(none)
```

A `diff` view of the above:
```patch
--- good	2019-11-04 18:13:12.000000000 -0800
+++ bad	2019-11-04 18:13:17.000000000 -0800
@@ -1,18 +1,19 @@
 Name        : pauditd
-Version     : 1.1.11_next
+Version     : 1.1.11-next
 Release     : 1
 Architecture: x86_64
 Install Date: (not installed)
-Group       : Development/Tools
+Group       : 
 Size        : 9052160
 License     : MIT
 Signature   : (none)
-Source RPM  : pauditd-1.1.11_next-1.src.rpm
-Build Date  : Mon Nov  4 18:12:08 2019
-Build Host  : MacBook-Pro
+Source RPM  : pauditd-1.1.11-next-1.src.rpm
+Build Date  : (none)
+Build Host  : (none)
 Relocations : (not relocatable)
 Packager    : engineering <engineering@pantheon.io>
+Vendor      : Pantheon Systems
 URL         : https://github.com/pantheon-systems/pauditd
-Summary     : go alternative to auditd
+Summary     : (none)
 Description :
-go alternative to auditd
+(none)
```

**Comment by joemiller** [comment]
I haven't used any of these tools before but they'll be my next attempt at comparing the headers: http://ftp.rpm.org/max-rpm/s1-rpm-file-format-rpm-tools.html

**Comment by caarlos0** [comment]
OK, here we go:

## group

we had a default before, need to add it back probably:

```
{{- with .Info.Overridables.RPM.Group }}
Group: {{ . }}
{{- else }}
Group: Development/Tools
{{- end }}
```

## build data and build host

I guess rpmbuild adds them, we may need to add them as well...

## vendor

should be fine having it now even though we didn't had it before.

## summary

we used to default to the first line of the description, I guess this one is also a problem:

```
Summary: {{ first_line .Info.Description }}
```

Will work on these on nfpm.

**Comment by joemiller** [comment]
There is a `HEADER TAGS` section of this doc which has a list of required -vs- optional header tags: https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-package-structure.html

Constant | Value | Type | Required?
-- | -- | -- | --
RPMTAG_NAME | 1000 | STRING | Yes
RPMTAG_VERSION | 1001 | STRING | Yes
RPMTAG_RELEASE | 1002 | STRING | Yes
RPMTAG_SUMMARY | 1004 | I18NSTRING | Yes
RPMTAG_DESCRIPTION | 1005 | I18NSTRING | Yes
RPMTAG_BUILDTIME | 1006 | INT32 | Optional
RPMTAG_BUILDHOST | 1007 | STRING | Optional
RPMTAG_SIZE | 1009 | INT32 | Yes
RPMTAG_LICENSE | 1014 | STRING | Yes
RPMTAG_GROUP | 1016 | I18NSTRING | Yes
RPMTAG_OS | 1021 | STRING | Yes
RPMTAG_ARCH | 1022 | STRING | Yes
RPMTAG_SOURCERPM | 1044 | STRING | Optional
RPMTAG_FILEVERIFYFLAGS | 1045 | INT32 | Optional
RPMTAG_ARCHIVESIZE | 1046 | INT32 | Optional
RPMTAG_RPMVERSION | 1064 | STRING | Optional
RPMTAG_CHANGELOGTIME | 1080 | INT32 | Optional
RPMTAG_CHANGELOGNAME | 1081 | STRING_ARRAY | Optional
RPMTAG_CHANGELOGTEXT | 1082 | STRING_ARRAY | Optional
RPMTAG_COOKIE | 1094 | STRING | Optional
RPMTAG_OPTFLAGS | 1122 | STRING | Optional
RPMTAG_PAYLOADFORMAT | 1124 | STRING | Yes
RPMTAG_PAYLOADCOMPRESSOR | 1125 | STRING | Yes
RPMTAG_PAYLOADFLAGS | 1126 | STRING | Yes
RPMTAG_RHNPLATFORM | 1131 | STRING | Deprecated
RPMTAG_PLATFORM | 1132 | STRING | Optional

A few required tags that might be missing based on the `rpm -qpi` output:
- Group
- Summary
- Description

**Comment by caarlos0** [comment]
yep, seems like!

will require a PR on rpmpack as well, already WIP


thanks for reporting this :)

**Comment by caarlos0** [comment]
releasing v0.120.6

@joemiller can you give it a try? :)

**Comment by joemiller** [comment]
@caarlos0 still getting 500 from packagecloud API

``` console
$ rpm -qpi dist/*rpm

Name        : pauditd
Version     : 1.1.11-next
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Tools
Size        : 9052160
License     : MIT
Signature   : (none)
Source RPM  : pauditd-1.1.11-next-1.src.rpm
Build Date  : (none)
Build Host  : (none)
Relocations : (not relocatable)
Packager    : engineering <engineering@pantheon.io>
Vendor      : Pantheon Systems
URL         : https://github.com/pantheon-systems/pauditd
Summary     : go alternative to auditd
Description :
go alternative to auditd
```

```
pushing dist/pauditd-v1.1.11-next-1572924171-x86_64.rpm... Traceback (most recent call last):
        23: from /usr/local/bin/package_cloud:22:in `<main>'
        22: from /usr/local/bin/package_cloud:22:in `load'
        21: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/bin/package_cloud:4:in `<top (required)>'
        20: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        19: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        18: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        17: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        16: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:108:in `push'
        15: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
        14: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:168:in `block in push'
        13: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:168:in `each'
        12: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:178:in `block (2 levels) in push'
        11: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
        10: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:182:in `block (3 levels) in push'
         9: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:242:in `create_package'
         8: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/repository.rb:52:in `create_package'
         7: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
         6: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
         5: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
         4: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/net/http.rb:920:in `start'
         3: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
         2: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
         1: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response': 500 Internal Server Error (RestClient::InternalServerError)
```

Not sure what the issue may be at this point. Perhaps missing build date and build host, although those are marked as optional tags

**Comment by caarlos0** [comment]
yeah, diff shows less things now:

```diff
2c2
< Version     : 1.1.11_next
---
> Version     : 1.1.11-next
10,12c10,12
< Source RPM  : pauditd-1.1.11_next-1.src.rpm
< Build Date  : Mon Nov  4 18:12:08 2019
< Build Host  : MacBook-Pro
---
> Source RPM  : pauditd-1.1.11-next-1.src.rpm
> Build Date  : (none)
> Build Host  : (none)
14a15
> Vendor      : Pantheon Systems
19d19
<
```

**Comment by caarlos0** [comment]
not sure about the `_next` vs `-next` thing 🤔

**Comment by caarlos0** [comment]
can you try to generate a pkg with a tag without `-next` to see how it goes?

**Comment by caarlos0** [comment]
at this point I'm pretty sure that is it, we used to have this on nfpm:

```
info.Version = strings.Replace(info.Version, "-", "_", -1)
```

**Comment by caarlos0** [comment]
although I think that what should actually happen is: 

```
Version     : 1.1.11
Release     : next
```

**Comment by caarlos0** [comment]
Got it, it happens if we call nfpm binary, but using as an API it doesn't, because the check is on the yaml parser func.

Will work on a proper fix tomorrow.

**Comment by caarlos0** [comment]
pushing v0.120.7, please give it a try @joemiller 🚀

**Comment by joemiller** [comment]
@caarlos0 still 500'ing

```console
$ curl -sL https://git.io/goreleaser | bash -s -- --snapshot --rm-dist

   • releasing using goreleaser 0.120.7...
   • loading config file       file=.goreleaser.yml

$ rpm -qpi dist/*rpm
Name        : pauditd
Version     : 1.1.11
Release     : next
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Tools
Size        : 9052160
License     : MIT
Signature   : (none)
Source RPM  : pauditd-1.1.11-next.src.rpm
Build Date  : (none)
Build Host  : (none)
Relocations : (not relocatable)
Packager    : engineering <engineering@pantheon.io>
Vendor      : Pantheon Systems
URL         : https://github.com/pantheon-systems/pauditd
Summary     : go alternative to auditd
Description :
go alternative to auditd

$ package_cloud push xx/xx/el/8 dist/*rpm
Pushing dist/pauditd-v1.1.11-next-1572965269-x86_64.rpm... Traceback (most recent call last):
        23: from /usr/local/bin/package_cloud:22:in `<main>'
        22: from /usr/local/bin/package_cloud:22:in `load'
        21: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/bin/package_cloud:4:in `<top (required)>'
        20: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        19: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        18: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        17: from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        16: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:108:in `push'
        15: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
        14: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:168:in `block in push'
        13: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:168:in `each'
        12: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:178:in `block (2 levels) in push'
        11: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
        10: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:182:in `block (3 levels) in push'
         9: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/cli/entry.rb:242:in `create_package'
         8: from /usr/local/lib/ruby/gems/2.6.0/gems/package_cloud-0.3.05/lib/package_cloud/repository.rb:52:in `create_package'
         7: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
         6: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
         5: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
         4: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/net/http.rb:920:in `start'
         3: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
         2: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
         1: from /usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/usr/local/lib/ruby/gems/2.6.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response': 500 Internal Server Error (RestClient::InternalServerError)
```

**Comment by caarlos0** [comment]
🙁

all required fields are there now, no idea why it is complaining...

only think that remains different is buil date and host 🙇‍♂️

**Comment by caarlos0** [comment]
I've just sent an email to packagecloud asking for advice on this.

**Comment by caarlos0** [comment]
Build time is an `int32`, is it supposed to be unix time? 🤔

**Comment by joemiller** [comment]
@caarlos0 i think so. I haven't found a definitive source yet, but found these ancillary docs/comments referencing unix epoch time

- https://github.com/rpm-software-management/rpm/issues/197
- http://www.blackperl.com/Perl-RPM/Constants.html (`The time/date when the package was created, expressed as a time() value (seconds since the epoch).`)
- https://refspecs.linuxfoundation.org/LSB_1.3.0/gLSB/gLSB.html#AEN19637

**Comment by caarlos0** [comment]
yeah, was what I figured as well...

**Comment by caarlos0** [comment]
can you try goreleaser master and see if the rpm works?

**Comment by joemiller** [comment]
That last link in the previous comment (https://refspecs.linuxfoundation.org/LSB_1.3.0/gLSB/gLSB.html#AEN19637) had some interesting rpm tags that were not mentioned in the fedora link from a couple days ago in this thread.

That led me to poking a bit more at the "good" rpm from goreleaser 0.119 and a "bad" one:

I'm not sure if this is the cause but it might be interesting to look into:

script are marked optional in the doc, but there are differences between the two RPMs:
```console
$ rpm -qp --scripts *GOOD.rpm
preinstall scriptlet (using /bin/sh):
# noop
postinstall scriptlet (using /bin/sh):
# noop
preuninstall scriptlet (using /bin/sh):
# noop
postuninstall scriptlet (using /bin/sh):
# noop

$ rpm -qp --scripts *BAD.rpm
$
```

```console
$ rpm -qp --requires *GOOD.rpm
/bin/sh
/bin/sh
/bin/sh
/bin/sh
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1

$ rpm -qp --requires *BAD.rpm
$
```

```console
$rpm -qp --provides *GOOD.rpm
pauditd = 1.1.11_next-1

$ rpm -qp --provides *BAD.rpm
pauditd = 1.1.11-next
```

**Comment by joemiller** [comment]
@caarlos0 victory!!

```console
Pushing dist/pauditd-v1.1.11-next-1573052483-x86_64.rpm... success!
```

**Comment by caarlos0** [comment]
🚀 

Awesome! This one was hard hahaha 

Thanks for all the help Joe! Will release and close this 👍

**Comment by caarlos0** [comment]
Pushed v0.120.8.

Should be fixed there!

Closing this.
