### ISSUE TITLE
Snap and parallel builds

### ISSUE THREAD

**Issue by lawrencegripper** [goreleaser/goreleaser#1715]
First up - GoReleaser is awesome and thanks for all the hard work thats gone into it. Happy to fix this one up as a PR if you agree with the change.

**Describe the bug**

When using Snap builds I see the following error intermittently. 

```
FileExistsError: [Errno 17] File exists: '/root/.cache/snapcraft/download'
```

Tracking down the code in snap it's a call in python which checks if a folder exists then, if it doesn't exist, attempts to create it. 

"/snap/snapcraft/current/lib/python3.6/site-packages/xdg/BaseDirectory.py", line 81

![image](https://user-images.githubusercontent.com/1939288/88973240-ae61aa00-d2ae-11ea-849d-758b9ea79a06.png)

In my example I'm building for an number of different architectures inside a docker container. I *think* the following code in GoReleaser

https://github.com/goreleaser/goreleaser/blob/10a237364b8fefefe52fad3605ed879afdafbec9/internal/pipe/snapcraft/snapcraft.go#L124-L127

is kicking off multiple instances of snapcraft, in my case 2, and this is causing a concurrency bug in the snapcraft python where two instances enter the check, both see the folder doesn't exist, then the first instance creates it and the second instance fails attempting to create it as it's already been done. Unlucky right? 😢

So I wasn't sure if this could be the case and I wanted proof - the way I proved it was to remove one of the `goarch` so I build just `arm64` instead of `386 & arm64` and problem was gone and fixed consistently 🎉

I think to resolve the issue the builds for snapcraft should be called serially rather than in parallel. If you can point me how to do this happy to submit a PR.

**To Reproduce**

Machine spec is going to influence things here, locally on i9 with lots of ram it happens every time. In GitHub actions CI I get anywhere between 1/2~1/10. 

Pull down this repo here https://github.com/lawrencegripper/azbrowse with branch `lg/reenablesnap` you can see an example of the failure here https://github.com/lawrencegripper/azbrowse/pull/263/checks?check_run_id=927272032

Run `IS_CI=true BUILD_NUMBER=1 make devcontainer-release` (this requires docker and nothing else). Run a few times and see the issue occur. 

**Expected behavior**

Snaps to be built. 

**Environment (please complete the following information):**

- OS: Linux in Docker
- OS version: Debian Stretch
- GoReleaser Version v0.140.1

**Additional context**

`snapcraft==4.0.7`

```
> ----------------------------------------------------- 
---------------> Run go releaser 
------------------------------------------------------- 

Running with --skip-publish as PUBLISH not set

   • releasing using goreleaser 0.132.1...
   • loading config file       file=.goreleaser.yml
   • running before hooks
   • loading environment variables
   • getting and validating git state
      • releasing v2.0.1, commit a186e09ba1593d0c7915ad1f7192d65f9cf3d5c4
   • parsing tag      
   • setting defaults 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • building binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images    
      • artifactory      
      • blobs            
      • homebrew tap formula
         • optimistically guessing `brew[0].installs`, double check
      • scoop manifests  
   • snapshotting     
      • pipe skipped              error=not a snapshot
   • checking ./dist  
      • --rm-dist is set, cleaning it up
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • writing                   changelog=dist/CHANGELOG.md
   • building binaries
      • building                  binary=/home/lawrence/source/personal/azbrowse/dist/all_windows_amd64/azbrowse.exe
      • building                  binary=/home/lawrence/source/personal/azbrowse/dist/all_linux_amd64/azbrowse
      • building                  binary=/home/lawrence/source/personal/azbrowse/dist/all_linux_386/azbrowse
      • building                  binary=/home/lawrence/source/personal/azbrowse/dist/all_darwin_386/azbrowse
      • building                  binary=/home/lawrence/source/personal/azbrowse/dist/all_darwin_amd64/azbrowse
      • building                  binary=/home/lawrence/source/personal/azbrowse/dist/all_windows_386/azbrowse.exe
   • archives         
      • creating                  archive=dist/azbrowse_windows_386.zip
      • creating                  archive=dist/azbrowse_darwin_amd64.tar.gz
      • creating                  archive=dist/azbrowse_windows_amd64.zip
      • creating                  archive=dist/azbrowse_darwin_386.tar.gz
      • creating                  archive=dist/azbrowse_linux_386.tar.gz
      • creating                  archive=dist/azbrowse_linux_amd64.tar.gz
   • creating source archive
      • pipe skipped              error=source pipe is disabled
   • linux packages   
      • creating                  arch=i386 file=dist/azbrowse_386.deb package=azbrowse_386.deb
      • creating                  arch=amd64 file=dist/azbrowse_amd64.deb package=azbrowse_amd64.deb
      • creating                  arch=i386 file=dist/azbrowse_386.rpm package=azbrowse_386.rpm
      • creating                  arch=amd64 file=dist/azbrowse_amd64.rpm package=azbrowse_amd64.rpm
   • snapcraft packages
      • creating                  arch=i386 snap=dist/azbrowse_386.snap
      • creating                  arch=amd64 snap=dist/azbrowse_amd64.snap
   ⨯ release failed after 59.28s error=failed to generate snap package: Traceback (most recent call last):
  File "/snap/snapcraft/current/bin/snapcraft", line 33, in <module>
    sys.exit(load_entry_point('snapcraft==4.0.7', 'console_scripts', 'snapcraft')())
  File "/snap/snapcraft/current/bin/snapcraft", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/snap/snapcraft/current/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/snap/snapcraft/current/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/__init__.py", line 341, in <module>
    from snapcraft.plugins.v1 import PluginV1 as BasePlugin  # noqa: F401
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/plugins/__init__.py", line 17, in <module>
    from ._plugin_finder import get_plugin_for_base  # noqa: F401
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/plugins/_plugin_finder.py", line 20, in <module>
    from snapcraft.internal import errors
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/__init__.py", line 17, in <module>
    from snapcraft.internal import cache  # noqa
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/cache/__init__.py", line 20, in <module>
    from ._snap import SnapCache  # noqa
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/cache/_snap.py", line 25, in <module>
    from snapcraft import file_utils, yaml_utils
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/yaml_utils.py", line 22, in <module>
    from snapcraft.project.errors import YamlValidationError
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/project/__init__.py", line 17, in <module>
    from ._project import Project  # noqa F401
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/project/_project.py", line 23, in <module>
    from snapcraft.internal.meta.snap import Snap
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/meta/snap.py", line 28, in <module>
    from snapcraft.internal.meta.package_repository import PackageRepository
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/meta/package_repository.py", line 24, in <module>
    from snapcraft.internal import repo
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/repo/__init__.py", line 27, in <module>
    from ._deb import Ubuntu  # noqa
  File "/snap/snapcraft/current/lib/python3.6/site-packages/snapcraft/internal/repo/_deb.py", line 48, in <module>
    BaseDirectory.save_cache_path("snapcraft", "download")
  File "/snap/snapcraft/current/lib/python3.6/site-packages/xdg/BaseDirectory.py", line 81, in save_cache_path
    os.makedirs(path)
  File "/snap/snapcraft/current/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.cache/snapcraft/download'

make: *** [Makefile:173: devcontainer-release] Error 1
```

**Comment by caarlos0** [comment]
Thanks for the bug report, will take a closer look soon.

For now, as a workaround, you can run goreleaser with `--parallelism=1` (which will affect everything, not just snap).

**Comment by lawrencegripper** [comment]
Thanks, I found another workaround which might help other too. If you pre-create the folders needed then there is no race condition in `snapcraft` as it doesn't handle the creation. 

Before calling `gorelaser` run 

```
mkdir -p $HOME/.cache/snapcraft/download
mkdir -p $HOME/.cache/snapcraft/stage-packages
```
Works my end and I get to keep parallel builds.

**Comment by lawrencegripper** [comment]
Closing this issue off as it's a Snapcraft issue not a GoReleaser thing. 

Bug tracking it file on Launchpad here: https://bugs.launchpad.net/snapcraft/+bug/1889741

**Comment by caarlos0** [comment]
ah neat, thanks for digging into this, sorry I missed the issue (somehow marked it as read before actually reading it I guess)

**Comment by caarlos0** [comment]
@lawrencegripper seems that this issue returned on snapcraft 4.5.4 🤔

https://github.com/goreleaser/goreleaser/runs/2131295521?check_suite_focus=true#step:9:87

**Comment by lawrencegripper** [comment]
Ah hopefully the ‘mkdir’ hack still works to resolve this one. I’ve not hit it again since adding that into my CI pipeline

**Comment by caarlos0** [comment]
> Ah hopefully the ‘mkdir’ hack still works to resolve this one. I’ve not hit it again since adding that into my CI pipeline

yeah it does...

**Comment by cjp256** [comment]
FWIW I've triaged this issue from the Snapcraft perspective and am working on a fix. I'll be happy to return and clean up your workaround once it has landed in stable :D

**Comment by caarlos0** [comment]
amazing, thanks @cjp256 🙏

**Comment by caarlos0** [comment]
hey @cjp256, any updates on this?

**Comment by caarlos0** [comment]
didn't happen again, so... closing
