### ISSUE TITLE
fix snapcraft tests on latest snapcraft versions

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/goreleaser#1843]
its failing with:

```--- FAIL: TestRunPipeWithName (0.58s)
    snapcraft_test.go:141:
        	Error Trace:	snapcraft_test.go:141
        	Error:      	Received unexpected error:
        	            	failed to generate snap package: Snapping...
        	            	Sorry, an error occurred in Snapcraft:
        	            	Failed to create snap, snap command failed:
        	            	stdout:

        	            	stderr:
        	            	2020/10/07 00:30:13.487491 container.go:213: in snap "testsnapname": path "mybin" does not exist
        	            	error: cannot pack "/var/folders/0z/y2vh6zjj0m92p065bzb5w3x00000gp/T/archivetest076617848/dist/foo_amd64/prime": snap is unusable due to missing files

        	            	Traceback (most recent call last):
        	            	  File "/usr/local/bin/snapcraft", line 8, in <module>
        	            	    sys.exit(run())
        	            	  File "/usr/local/Cellar/snapcraft/4.3/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
        	            	    return self.main(*args, **kwargs)
        	            	  File "/usr/local/Cellar/snapcraft/4.3/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
        	            	    rv = self.invoke(ctx)
        	            	  File "/usr/local/Cellar/snapcraft/4.3/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
        	            	    return _process_result(sub_ctx.command.invoke(sub_ctx))
        	            	  File "/usr/local/Cellar/snapcraft/4.3/libexec/lib/python3.8/site-packages/snapcraft/cli/_command.py", line 88, in invoke
        	            	    return super().invoke(ctx)
        	            	  File "/usr/local/Cellar/snapcraft/4.3/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
        	            	    return ctx.invoke(self.callback, **ctx.params)
        	            	  File "/usr/local/Cellar/snapcraft/4.3/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
        	            	    return callback(*args, **kwargs)
        	            	  File "/usr/local/Cellar/snapcraft/4.3/libexec/lib/python3.8/site-packages/snapcraft/cli/lifecycle.py", line 372, in pack
        	            	    _pack(directory, output=output)
        	            	  File "/usr/local/Cellar/snapcraft/4.3/libexec/lib/python3.8/site-packages/snapcraft/cli/lifecycle.py", line 220, in _pack
        	            	    snap_filename = _run_pack(command)
        	            	  File "/usr/local/Cellar/snapcraft/4.3/libexec/lib/python3.8/site-packages/snapcraft/cli/lifecycle.py", line 189, in _run_pack
        	            	    raise RuntimeError(
        	            	RuntimeError: Failed to create snap, snap command failed:
        	            	stdout:

        	            	stderr:
        	            	2020/10/07 00:30:13.487491 container.go:213: in snap "testsnapname": path "mybin" does not exist
        	            	error: cannot pack "/var/folders/0z/y2vh6zjj0m92p065bzb5w3x00000gp/T/archivetest076617848/dist/foo_amd64/prime": snap is unusable due to missing files

        	            	We would appreciate it if you created a bug report at
        	            	https://launchpad.net/snapcraft/+filebug with the above text included.
        	            	You can find the traceback in file '/var/folders/0z/y2vh6zjj0m92p065bzb5w3x00000gp/T/tmpb163ww_m/trace.txt'.
        	Test:       	TestRunPipeWithName
FAIL
FAIL	github.com/goreleaser/goreleaser/internal/pipe/snapcraft	2.748s
FAIL
```

We'll need to update the broken tests so they pass again.

My snap version:

```
❯ snap --version
snap    2.46
snapd   unavailable
series  16
darwin  -
kernel  19.6.0 (amd64)
```

**Comment by sasha27** [comment]
@caarlos0 has this been picked up? If not then I can look into it. Please let me know which packages I can look into and how to set up the dev/testing environment. Thank you!

**Comment by caarlos0** [comment]
hey, you just need to look into the `snapcraft` package. 

Setup guide can be found in https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md 

Thanks!

**Comment by irgendwr** [comment]
@caarlos0 I also took a look at this since there has been no recent activity and I could submit a fix soon, but I have a few questions first:

Q1: What is the point of the test case `TestRunPipeWithBinaryInDir`?
It was introduced in c5bd4021fdce43b5dca13c35e32d1cb467d3a426 from #1002 but apart from removing the hard-coded binary name this commit makes no sense at all to me.

`addBinaries(t, ctx, "foo", dist, "bin/mybin")` seems to be the relevant part of the test, but it sets the artifacts **name** to `bin/mybin` instead of putting something in a subdirectory (as the test name seems to indicate). The name is then trimmed to `mybin` in func `create` of `snapcraft.go` because of this: https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/snapcraft/snapcraft.go#L226

Q2: Why is `filepath.Base` used on the ___Name___ and not the ___Path___?

Q3: Can an `Artifact.Name` be a path? I would assume that it is not a path because that should be in `Artifact.Path`.

I don't understand how the snapcraft tests could have worked ever worked at all, because the `command` in most tests is `mybin` while the binary is named `foo`. The only way I see that this could have worked is probably because in previous versions snapcraft might not have validated whether `command` was valid.

Q4: What should the binary name be? `foo` or `mybin`? Because the `command` has to be the same as the binary name.

**Comment by irgendwr** [comment]
#1862 would fix this. I've marked it as a draft because of the open questions in my comment above.

**Comment by caarlos0** [comment]
hey, sorry for the late response, I'm moving to another state, so time is very limited (more than usual heh)...


Q1: I honestly don't remember, maybe @SimonBarendse can weight in?
Q2: Not sure, probably its wrong 🤔 
Q3: No, it shouldn't. Maybe thats the source of confusion here? (wrongly setting a path in name) Also, yes, pretty sure snapcraft didn't validate that before...
Q4: On the tests? I think either is fine if equal to command, as you stated.

**Comment by SimonBarendse** [comment]
Hey @caarlos0, best of luck with moving!

Unfortunately, I cannot give a definite answer to the question. I'll try to explain as best as I can remember the context of the PR I submitted. Hope that helps.

In [the SecretHub CLI goreleaser config](https://github.com/secrethub/secrethub-cli/blob/v0.41.2/.goreleaser.yml#L6), we're using `bin/secrethub` as the binary name, so that the binary ends up in a `bin` directory, as documented [here](https://github.com/goreleaser/goreleaser/blob/cc3567cde94c8840e4cd7f0afd0e9e2b8ee565a2/www/docs/customization/build.md#L30).

I've submitted #1002 because setting `builds.binary` to a path was causing issues with the snap pipe, as the metadata was stored under the "secrethub" key, while the snap pipe was looking it up under "bin/secrethub". The PR fixed this problem by looking it up under the "secrethub" key as well.

@caarlos0 Do you know if setting the binary name to a path could also cause the artifact name to be set to a path (Q3)?

Hope this helps!
