### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by blacktop** [goreleaser/goreleaser#186]
OSX 10.12.4

```bash
Releasing to GitHub
 -> Creating or updating release v0.1.0 on maliceio/malice
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1356a95]

goroutine 1 [running]:
github.com/goreleaser/goreleaser/client.(*githubClient).CreateRelease(0xc4204d2020, 0xc4200bc840, 0xc420156300, 0x7a, 0xc420156300, 0x7a, 0x61300a0a676f6c65)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/client/github.go:110 +0x255
github.com/goreleaser/goreleaser/pipeline/release.doRun(0xc4200bc840, 0x1692500, 0xc4204d2020, 0xc420127188, 0x10dac74)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/pipeline/release/release.go:37 +0x2ec
github.com/goreleaser/goreleaser/pipeline/release.Pipe.Run(0xc4200bc840, 0xc4201271b0, 0x10dad41)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/pipeline/release/release.go:25 +0x4d
github.com/goreleaser/goreleaser/pipeline/release.(*Pipe).Run(0x16df1c0, 0xc4200bc840, 0x1, 0xc42015c120)
	<autogenerated>:2 +0x4f
main.main.func1(0xc4200a0280, 0xc4200a0280, 0xc420053b87)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/main.go:96 +0x41b
github.com/goreleaser/goreleaser/vendor/github.com/urfave/cli.HandleAction(0x13eab00, 0x14a3e58, 0xc4200a0280, 0xc420018600, 0x0)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/goreleaser/goreleaser/vendor/github.com/urfave/cli.(*App).Run(0xc4200ba340, 0xc42000a380, 0x2, 0x2, 0x0, 0x0)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/vendor/github.com/urfave/cli/app.go:259 +0x70d
main.main()
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/main.go:104 +0x45d
```

I have the `GITHUB_TOKEN` set.

**Comment by caarlos0** [comment]
I'll have a look.

**Comment by caarlos0** [comment]
@blacktop can you try v0.11.1 ?

**Comment by blacktop** [comment]
works great thanks! 👍
