### ISSUE TITLE
[Bug]: Index Out Of Range for gist.github.com

### ISSUE THREAD

**Issue by cimnine** [goreleaser/goreleaser#2414]
### What happened?

When I was preparing another goreleaser bug, I was using gist.github.com as a sample repository.
When I ran, then the following error occured:

```bash
$ goreleaser release --skip-publish --rm-dist
   • releasing...
   • could not find a config file, using defaults...
   • loading environment variables
   • getting and validating git state
      • building...               commit=9bd0f955cde0b405962e483a6c7b27770a91c956 latest tag=v1.0.0
   • parsing tag
   • running before hooks
   • setting defaults
      • snapshotting
      • github/gitlab/gitea releases
panic: runtime error: index out of range [-1]

goroutine 10 [running]:
github.com/goreleaser/goreleaser/internal/git.ExtractRepoFromURL(0xc00004b0e0, 0x30, 0x3, 0x5, 0xc0004ab2c0, 0x39)
	github.com/goreleaser/goreleaser/internal/git/config.go:38 +0x285
github.com/goreleaser/goreleaser/internal/git.ExtractRepoFromConfig(0x2110a20, 0x2fd7338, 0x21115a0, 0xc000535d10, 0xc0000a0100, 0x24c5d18)
	github.com/goreleaser/goreleaser/internal/git/config.go:20 +0x12b
github.com/goreleaser/goreleaser/internal/pipe/release.Pipe.Default(0xc000828400, 0x24, 0x0)
	github.com/goreleaser/goreleaser/internal/pipe/release/release.go:80 +0x48b
github.com/goreleaser/goreleaser/internal/middleware.ErrHandler.func1(0xc000828400, 0xc00004b020, 0x24)
	github.com/goreleaser/goreleaser/internal/middleware/error.go:13 +0x33
github.com/goreleaser/goreleaser/internal/middleware.Logging.func1(0xc000828400, 0x0, 0x0)
	github.com/goreleaser/goreleaser/internal/middleware/logging.go:33 +0x18e
github.com/goreleaser/goreleaser/internal/pipe/defaults.Pipe.Run(0xc000828400, 0x18, 0x0)
	github.com/goreleaser/goreleaser/internal/pipe/defaults/defaults.go:40 +0x1ca
github.com/goreleaser/goreleaser/internal/middleware.ErrHandler.func1(0xc000828400, 0xc000049128, 0x18)
	github.com/goreleaser/goreleaser/internal/middleware/error.go:13 +0x33
github.com/goreleaser/goreleaser/internal/middleware.Logging.func1(0xc000828400, 0x0, 0x0)
	github.com/goreleaser/goreleaser/internal/middleware/logging.go:33 +0x18e
github.com/goreleaser/goreleaser/cmd.releaseProject.func1(0x0, 0x0)
	github.com/goreleaser/goreleaser/cmd/release.go:108 +0x11b
github.com/caarlos0/ctrlc.(*Ctrlc).Run.func1(0xc00007e290, 0xc0005356a0)
	github.com/caarlos0/ctrlc@v1.0.0/ctrlc.go:39 +0x27
created by github.com/caarlos0/ctrlc.(*Ctrlc).Run
	github.com/caarlos0/ctrlc@v1.0.0/ctrlc.go:38 +0x65
```

and

```bash
$ goreleaser check
   • could not find a config file, using defaults...
   • checking config:
      • snapshotting
      • github/gitlab/gitea releases
panic: runtime error: index out of range [-1]

goroutine 25 [running]:
github.com/goreleaser/goreleaser/internal/git.ExtractRepoFromURL(0xc000178150, 0x30, 0x3, 0x5, 0xc0004d62c0, 0x39)
	github.com/goreleaser/goreleaser/internal/git/config.go:38 +0x285
github.com/goreleaser/goreleaser/internal/git.ExtractRepoFromConfig(0x2110a20, 0x2fd7338, 0x21115a0, 0xc000118f50, 0xc000138100, 0x24c5d18)
	github.com/goreleaser/goreleaser/internal/git/config.go:20 +0x12b
github.com/goreleaser/goreleaser/internal/pipe/release.Pipe.Default(0xc000502d00, 0x24, 0x0)
	github.com/goreleaser/goreleaser/internal/pipe/release/release.go:80 +0x48b
github.com/goreleaser/goreleaser/internal/middleware.ErrHandler.func1(0xc000502d00, 0xc000178090, 0x24)
	github.com/goreleaser/goreleaser/internal/middleware/error.go:13 +0x33
github.com/goreleaser/goreleaser/internal/middleware.Logging.func1(0xc000502d00, 0x0, 0x0)
	github.com/goreleaser/goreleaser/internal/middleware/logging.go:33 +0x18e
github.com/goreleaser/goreleaser/internal/pipe/defaults.Pipe.Run(0xc000502d00, 0xc0005a6018, 0x18)
	github.com/goreleaser/goreleaser/internal/pipe/defaults/defaults.go:40 +0x1ca
github.com/goreleaser/goreleaser/cmd.newCheckCmd.func1.1(0x0, 0x0)
	github.com/goreleaser/goreleaser/cmd/check.go:46 +0xe5
github.com/caarlos0/ctrlc.(*Ctrlc).Run.func1(0xc000118280, 0xc0003c3850)
	github.com/caarlos0/ctrlc@v1.0.0/ctrlc.go:39 +0x27
created by github.com/caarlos0/ctrlc.(*Ctrlc).Run
	github.com/caarlos0/ctrlc@v1.0.0/ctrlc.go:38 +0x65
```

### How can we reproduce this?

```bash
git clone https://gist.github.com/cimnine/eb61e0bbd63b509c21ff33058c408eee reproduce
cd reproduce
goreleaser release --skip-publish --rm-dist
```

### goreleaser version

```bash
$ goreleaser --version
goreleaser version 0.175.0
commit: 5e006eb236284c29143341e48c2f692826865d47
built by: homebrew

https://goreleaser.com
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

> If I run `goreleaser check` it shows no errors

`goreleaser check` panics as well, so the answer would actually be no.

> By submitting this issue, you agree to follow our Code of Conduct

The _Code of Conduct_ links to https://example.com .

**Comment by caarlos0** [comment]
goreleaser is not expected to be run using gist as a repository, therefore this will not be fixed.

**Comment by cimnine** [comment]
May I suggest to add a check (e.g. to `goreleaser check`) which ensures this precondition and presents a nice error message that _goreleaser is not expected to be run using a gist as repository_. This would be more user-friendly than a panic.

**Comment by caarlos0** [comment]
not sure its worth it, all these years and this is the first time I hear of anyone attempting this...

**Comment by caarlos0** [comment]
yeah, the panic itself should be better, handled in #2416
