### ISSUE TITLE
Build failed in travis when use goreleaser

### ISSUE THREAD

**Issue by codeskyblue** [goreleaser/goreleaser#83]
This is log <https://travis-ci.org/openatx/wdaproxy/builds/192289771>
```
The command "go test -v ./..." exited with 0.
after_success
0.37s$ test -n "$TRAVIS_TAG" && curl -s https://raw.githubusercontent.com/goreleaser/get/master/latest | bash
Setting defaults...
Loading data from environment variables...
Gathering Git data...
Filling repositories data...
panic: runtime error: index out of range
goroutine 1 [running]:
panic(0x79c740, 0xc42000c160)
	/home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/goreleaser/goreleaser/pipeline/repos.split(0x0, 0x0, 0xc4200d8020, 0x7, 0xc4200d8028, 0x8)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/pipeline/repos/repos.go:34 +0x95
github.com/goreleaser/goreleaser/pipeline/repos.Pipe.Run(0xc4200156b0, 0xc42004d970, 0x45cac1)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/pipeline/repos/repos.go:24 +0xf7
github.com/goreleaser/goreleaser/pipeline/repos.(*Pipe).Run(0x9f2ef0, 0xc4200156b0, 0x1, 0x777b00)
	<autogenerated>:2 +0x56
main.main.func1(0xc420080500, 0xc420080500, 0xc42004dc47)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/main.go:61 +0x2e8
github.com/goreleaser/goreleaser/vendor/github.com/urfave/cli.HandleAction(0x784fe0, 0x83b138, 0xc420080500, 0xc42001a480, 0x0)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/goreleaser/goreleaser/vendor/github.com/urfave/cli.(*App).Run(0xc42007cb60, 0xc42000c2e0, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/vendor/github.com/urfave/cli/app.go:259 +0x74f
main.main()
	/home/travis/gopath/src/github.com/goreleaser/goreleaser/main.go:69 +0x1dd
```

**Comment by caarlos0** [comment]
refs #81
